### ISSUE TITLE
GoldHen1.1 Kernel Panic when power off the PS4 system

### ISSUE THREAD

**Issue by nalawneh-co** [hippie68/hippie68.github.io#2]
PS4 Firmware: 7.50
Description: If I tried to poweroff the PS4 during running the GoldHen1.1 it seems there are a kernel panic is happen and device freeze and makes a sound then the device is shutdown.

**Comment by hippie68** [comment]
This is probably caused by the jailbreak itself (which is not my work) being still unstable. I'm afraid it has nothing to do with the website in particular. I did just double-check the GoldHEN 1.1 7.50 payload to make sure it is the latest available version.
You could try HEN 2.1.3b, which claims to fix freezing issues.

**Comment by nalawneh-co** [comment]
thank you, I will close this issue.
